### ISSUE TITLE
Mobile View padding is still there on the left

### ISSUE THREAD

**Issue by sohilpandya** [sohilpandya/Bidlt#134]
@katpas have you seen this... seems to be some css causing this. you have any idea as to why this might be happening?

![screen shot 2016-03-28 at 11 18 36](https://cloud.githubusercontent.com/assets/2305591/14076522/42fac4e2-f4da-11e5-98f9-1fb38140bee8.png)

**Comment by sohilpandya** [comment]
I have created a PR that will fix this issue.

**Comment by katpas** [comment]
I deleted the css we had in their originally when I was moving stuff around. Sorry.
