### ISSUE TITLE
Create List View Calendar

### ISSUE THREAD

**Issue by katpas** [sohilpandya/Bidlt#15]
- Each component is an event with dummy object which contains multiple events
- When you click on a job component it links to detailed view modal

**Comment by sohilpandya** [comment]
Pass down props for:

Title
Data for Agenda (i.e. event.js file)

**Comment by sohilpandya** [comment]
Change name of the events. builder firnedly.

**Comment by katpas** [comment]
Not passing down props as same across all pages.
