### ISSUE TITLE
Google Map Prop for Zoom in/Out Disable. (Zoom on scroll disable)

### ISSUE THREAD

**Issue by sohilpandya** [sohilpandya/Bidlt#78]

**Comment by katpas** [comment]
I started looking at this as was looking at changing the markers etc.

The thing is setting scrollwheel{false} but it's hard to work out where as there's a lot of es6. Difference between the options of the map components and the props for it. I think we're setting options at the moment but some of the elements are only accessible via props.

**Comment by katpas** [comment]
Also, babel translate doesn't work because of all the jsx

**Comment by sohilpandya** [comment]
@katpas please merge the PR, I have fixed this issue.  :+1:
